#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt install -y haproxy

sudo echo -e "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   server 2385-web-01 34.73.144.167
   server 2385-web-02 34.74.56.196" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo sed -i "2s/0/1/g" /etc/default/haproxy

sudo service haproxy restart
